---
k3s_version: ""
# https://update.k3s.io/v1-release/channels
k3s_channel: stable
ansible_user: pirate
systemd_dir: "/etc/systemd/system"
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
# https://github.com/rancher/docs/issues/2707
extra_server_args: "--node-taint CriticalAddonsOnly=true:NoExecute"
extra_agent_args: ""

# nfs-client
nfs_server: 192.168.1.192
nfs_path: "/home/pi/nas/nfs"
nfs_chart_version: 1.2.9
storage_class: "managed-nfs-storage"
