---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        name: Run yamllint
        description: Lint yaml files
    # https://github.com/openstack/tripleo-ci/blob/master/.pre-commit-config.yaml#L24-L34
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        name: Run ansible-lint
        description: Lint ansible files
        always_run: true
        pass_filenames: false
        # do not add file filters here as ansible-lint does not give reliable
        # results when called with individual files.
        # https://github.com/ansible/ansible-lint/issues/611
        verbose: false
        entry: env ANSIBLE_LIBRARY=./library ansible-lint --force-color -p -v .
        additional_dependencies:
          - 'ansible<2.10'
