---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  tags: ['base']

- hosts: master
  become: yes
  roles:
    - role: k3s/master
  tags: ['base']

- hosts: nodes
  become: yes
  roles:
    - role: k3s/node
  tags: ['base']

- hosts: master
  become: no
  gather_facts: no
  collections:
    - kubernetes.core

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: ~/.kube/config
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  roles:
    - role: scp-config
      tags: ['scp-config']
#    - role: system-upgrade
#      tags: ['system-upgrade']
    - role: managed-nfs-storage
      tags: ['managed-nfs-storage']
