---
- name: Create managed-nfs-storage namespace.
  k8s:
    name: managed-nfs-storage
    api_version: v1
    kind: Namespace
    state: present

- name: Add stable chart repo.
  helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"

- name: Deploy nfs-client-provisioner chart.
  helm:
    name: managed-nfs-client
    chart_ref: stable/nfs-client-provisioner
    chart_version: '{{ nfs_chart_version }}'
    release_namespace: "{{ storage_class }}"
    state: present
    values:
      image:
        repository: quay.io/external_storage/nfs-client-provisioner-arm
      nfs:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"
      storageClass:
        create: true
        name: managed-nfs-storage
